---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: common-file-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
  storageClassName:  dep-private-common